### PR TITLE
support for Laravel 5.2

### PR DESCRIPTION
**Pull request by anand-patel**

### CODE REVIEW

**Comment by jadjoubran** [comment]
Awesome, thanks!
But shouldn't we make it 5.1 || 5.2?
In order to keep support for 5.1

**Comment by anand-patel** [comment]
Yes we can do that in order to support 5.1.

**Comment by jadjoubran** [comment]
Can you fix it please?
then I'll merge and release with a new tag

**Comment by jadjoubran** [comment]
Hi @anand-patel 
Any update on the below?
Thanks!

**Pull request closed without merging**
