### PR TITLE
Applied fixes from StyleCI

### PR DESCRIPTION
**Pull request by jadjoubran**
This pull request applies code style fixes from an analysis carried out by [StyleCI](https://styleci.io).

---

For more information, click [here](https://styleci.io/analyses/z9mp96).

### CODE REVIEW

**Comment by jadjoubran** [comment]
@flick36 see how awesome StyleCI is? It's developed by @grahamCampbell

**Comment by flick36** [comment]
hahaha yeah i know, but i supposedly clean the code with a plugin on sublime, that's why i didn't understand why it haven't pass xD never completly trust plugins lesson learned

**Comment by jadjoubran** [comment]
I think you're missing the `editorconfig` plugin

**Comment by GrahamCampbell** [comment]
;)

**Pull request merged**
