### PR TITLE
Added support for configuring stylesheet language

### PR DESCRIPTION
**Pull request by vikpe**
Generate less, scss or css  for pages and components by setting the preferred stylesheet language in config/generators.php (less by default).

### CODE REVIEW

**Comment by jadjoubran** [comment]
That's a great addition, thanks! 😄 
I'd suggest having the argument under the `suffix` in order to maintain consistency
Something like:
`suffix.stylesheet`

**Comment by vikpe** [comment]
Done!

**Comment by jadjoubran** [comment]
Thanks! 😄

**Comment by jadjoubran** [comment]
Available in 2.6.0

**Pull request merged**
