### PR TITLE
Added option to create page in a custom folder

### PR DESCRIPTION
**Pull request by flick36**
I still don't know why the shorcut doesn't work, i'll have to investigate that

And i don't know why the StyleCI is failing .-.

### CODE REVIEW

**Comment by jadjoubran** [comment]
Thanks flick36!
Don't worry about styleCI, it'll automatically create a PR to fix the styles.
However I was thinking that there was an easier way to create pages in custom folders.. How about this:
`php artisan ng:page accounts/login`
without needing to pass the path argument `php artisan ng:page login --path=accounts` which is also a bit confusing

**Comment by flick36** [comment]
Of course, i can make another PR or just modify this one if you want it that way, i just used --path because some artisan commands already do it that way, but of course i'll create/edit another/this PR later i have a meeting right now :stuck_out_tongue_winking_eye:

**Comment by jadjoubran** [comment]
Yes it would be great if you can modify this one, thanks!
I'll squash the commits before merging.
It would be great if you can check if a file exists first, instead of overwriting

**Comment by jadjoubran** [comment]
Let me know if you need help 😄

**Comment by flick36** [comment]
Updated, let me know what you think

**Comment by jadjoubran** [comment]
Looks great, thanks! 😄 
Would you mind just renaming `$myArray` into something more useful (maybe pathsArray)

**Comment by flick36** [comment]
Done

**Comment by jadjoubran** [comment]
Thanks!

**Pull request merged**
