### PR TITLE
Fork synced

### PR DESCRIPTION
**Pull request by MatteoMeil**
Synced repo in order to complete #46

### CODE REVIEW

**Comment by jadjoubran** [comment]
Thanks for this Matteo! It will take me around a week or two to be able to review it
Will let you know soon

**Comment by MatteoMeil** [comment]
Recently i found a bug in older version of Laravel: i used
replaceNamespace() method in commands' constructor but it has been
introduced in newer versions so it must be changed with addNamespace() to
guarantee compatibility with older versions of Laravel.
If you could make these changes before merge would be great

Matteo Milanese

Il ven 14 set 2018, 12:11 Jad Joubran <notifications@github.com> ha scritto:

**Comment by MatteoMeil** [comment]
I close this PR in order to open another PR to fix that bug

**Comment by jadjoubran** [comment]
Thanks 👍

**Pull request closed without merging**
